import { all_routes } from "../../../feature-module/routes/all_routes";

export const header = [
  {
    tittle: "Inicio",
    base: "index",
    icon: "",
    showAsTab: false,
    separateRoute: false,
    menu: [
      {
        menuValue: "Inicio",
        route: all_routes.index,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
    ],
  },
  {
    tittle: "Propiedades",
    base: "listings",
    icon: "expand_more",
    showAsTab: false,
    separateRoute: false,
    menu: [
      {
        menuValue: "Comprar propiedad",
        hasSubRoute: true,
        showSubRoute: true,
        showAsTab2: false,
        subMenus: [
          {
            menuValue: "Comprar en cuadrícula",
            route: all_routes.buyPropertyGrid,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: "Detalles de compra",
            route: all_routes.buyPropertyGrid,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
        ],
      },
      {
        menuValue: "Alquilar propiedad",
        hasSubRoute: true,
        showSubRoute: true,
        showAsTab2: false,
        subMenus: [
          {
            menuValue: "Alquilar en cuadrícula",
            route: all_routes.rentPropertyGrid,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: "Detalles de alquiler",
            route: all_routes.rentPropertyGrid,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
        ],
      },
    ],
  },
  {
    tittle: "Agentes",
    showAsTab: false,
    separateRoute: false,
    base: "agent",
    icon: "expand_more",
    menu: [
      {
        menuValue: "Agentes en cuadrícula",
        route: all_routes.agentGrid,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
      {
        menuValue: "Detalles del agente",
        route: all_routes.agentDetails,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
    ],
  },
  {
    tittle: "Inmobiliarias",
    showAsTab: false,
    separateRoute: false,
    base: "agency",
    icon: "expand_more",
    menu: [
      {
        menuValue: "Inmobiliarias en cuadrícula",
        route: all_routes.agencyGrid,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
      {
        menuValue: "Detalles de la inmobiliaria",
        route: all_routes.agencyDetails,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
    ],
  },
  {
    tittle: "Páginas",
    showAsTab: false,
    separateRoute: false,
    base: "pages",
    icon: "expand_more",
    menu: [
      {
        menuValue: "Sobre nosotros",
        route: all_routes.aboutUs,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
      {
        menuValue: "Autenticación",
        hasSubRoute: true,
        showSubRoute: true,
        showAsTab2: false,
        subMenus: [
          {
            menuValue: "Registrarse",
            route: all_routes.signup,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: "Iniciar sesión",
            route: all_routes.signin,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: "Olvidé mi contraseña",
            route: all_routes.forgotPassword,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: "Restablecer contraseña",
            route: all_routes.resetPassword,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
        ],
      },
      {
        menuValue: "Detalles de la factura",
        route: all_routes.invoiceDetails,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
      {
        menuValue: "Contáctanos",
        route: all_routes.contactUs,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
      {
        menuValue: "Lista de deseos",
        route: all_routes.wishlist,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
      {
        menuValue: "Página de error",
        hasSubRoute: true,
        showSubRoute: true,
        showAsTab2: false,
        subMenus: [
          {
            menuValue: "Error 404",
            route: all_routes.error404,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
          {
            menuValue: "Error 500",
            route: all_routes.error500,
            hasSubRoute: false,
            showSubRoute: false,
            subMenus: [],
          },
        ],
      },
      {
        menuValue: "Precios",
        route: all_routes.pricing,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
      {
        menuValue: "Preguntas frecuentes",
        route: all_routes.faq,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
      {
        menuValue: "Galería",
        route: all_routes.gallery,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
      {
        menuValue: "Nuestro equipo",
        route: all_routes.ourTeam,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
      {
        menuValue: "Testimonios",
        route: all_routes.testimonial,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
      {
        menuValue: "Términos y condiciones",
        route: all_routes.termsCondition,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
      {
        menuValue: "Política de privacidad",
        route: all_routes.privacyPolicy,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
      {
        menuValue: "Mantenimiento",
        route: all_routes.maintenance,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
      {
        menuValue: "Próximamente",
        route: all_routes.comingSoon,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
    ],
  },
  {
    tittle: "Blog",
    showAsTab: false,
    separateRoute: false,
    base: "blog",
    icon: "expand_more",
    menu: [
      {
        menuValue: "Lista del blog",
        route: all_routes.blogList,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
      {
        menuValue: "Blog en cuadrícula",
        route: all_routes.blogGrid,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
      {
        menuValue: "Detalles del blog",
        route: all_routes.blogGrid,
        hasSubRoute: false,
        showSubRoute: false,
        subMenus: [],
      },
    ],
  },
];
