const mongoose = require('mongoose');

const ChecklistItemSchema = new mongoose.Schema({
  text: { type: String, required: true },
  done: { type: Boolean, default: false },
  doneAt: { type: Date },
  doneBy: { type: String },
}, { _id: true });

const DelegationSchema = new mongoose.Schema({
  fromUserId: { type: String, required: true },
  fromUserName: { type: String, default: '' },
  toUserId: { type: String, required: true },
  toUserName: { type: String, default: '' },
  reason: { type: String, default: '' },
  delegatedAt: { type: Date, default: Date.now },
}, { _id: true });

const TareaSchema = new mongoose.Schema(
  {
    title: { type: String, required: true, trim: true },
    description: { type: String, default: '' },
    // Keep legacy field for backward compat
    summary: { type: String, default: '' },

    status: {
      type: String,
      enum: [
        'pendiente', 'en_progreso', 'en_revision', 'completada', 'cancelada',
        // Legacy values kept for backward compat
        'Open', 'InProgress', 'Testing', 'Close',
      ],
      default: 'pendiente',
      index: true,
    },
    priority: { type: String, enum: ['urgente', 'alta', 'media', 'baja', 'Alta', 'Media', 'Baja'], default: 'media' },

    // Assignment
    assigneeId: { type: String, default: '', index: true },
    assigneeName: { type: String, default: '' },
    creatorId: { type: String, default: '' },
    creatorName: { type: String, default: '' },
    // Legacy field kept for backward compat
    agente: { type: String, default: '' },
    agenteId: { type: String, default: '', index: true },

    // Team
    teamId: { type: String, default: '', index: true },
    teamName: { type: String, default: '' },

    // Dates
    dueDate: { type: Date },
    startDate: { type: Date },
    completedAt: { type: Date },
    completed: { type: Boolean, default: false },

    // Labels / tags
    labels: [{ type: String }],
    tags: [{ type: String }],

    // Checklist
    checklist: [ChecklistItemSchema],

    // References
    clienteId: { type: String, default: '' },
    clienteNombre: { type: String, default: '' },
    propiedadId: { type: String, default: '' },
    propiedadTitulo: { type: String, default: '' },
    operacionId: { type: String, default: '' },

    // Delegation history
    delegations: [DelegationSchema],

    // Kanban
    kanbanColumn: { type: String, default: 'pendiente', index: true },
    position: { type: Number, default: 0 },

    // Automation origin
    automationRuleId: { type: String, default: '' },
    isAutoGenerated: { type: Boolean, default: false },

    createdBy: { type: String },
    metadata: { type: Object, default: {} },
  },
  { timestamps: true }
);

TareaSchema.index({ assigneeId: 1, status: 1 });
TareaSchema.index({ teamId: 1, status: 1 });
TareaSchema.index({ dueDate: 1, status: 1 });
TareaSchema.index({ creatorId: 1 });

module.exports = mongoose.model('Tarea', TareaSchema);
