const fechasImportantesArgentina = [
  {
    codigo: 'año_nuevo',
    nombre: 'Año Nuevo',
    descripcion: 'Celebración del inicio del nuevo año',
    tipo: 'feriado_nacional',
    mes: 1,
    dia: 1,
    esFechaFija: true,
    segmentacion: { genero: 'todos' },
    plantillaTitulo: '¡Feliz Año Nuevo, {{cliente.nombre}}!',
    plantillaMensaje: 'Desde {{empresa.nombre}} le deseamos un año lleno de éxitos, prosperidad y nuevas oportunidades. ¡Que todos sus proyectos inmobiliarios se hagan realidad!',
    prioridad: 'alta',
    activo: true,
  },
  {
    codigo: 'dia_mujer',
    nombre: 'Día Internacional de la Mujer',
    descripcion: 'Reconocimiento a las mujeres',
    tipo: 'dia_especial',
    mes: 3,
    dia: 8,
    esFechaFija: true,
    segmentacion: { genero: 'femenino' },
    plantillaTitulo: '¡Feliz Día de la Mujer, {{cliente.nombre}}!',
    plantillaMensaje: 'En este día tan especial, desde {{empresa.nombre}} queremos reconocer tu fortaleza, valentía y dedicación. ¡Feliz Día Internacional de la Mujer!',
    prioridad: 'alta',
    activo: true,
  },
  {
    codigo: 'dia_memoria',
    nombre: 'Día Nacional de la Memoria',
    descripcion: 'Día de la Memoria por la Verdad y la Justicia',
    tipo: 'feriado_nacional',
    mes: 3,
    dia: 24,
    esFechaFija: true,
    segmentacion: { genero: 'todos' },
    plantillaTitulo: 'Día de la Memoria',
    plantillaMensaje: 'Hoy conmemoramos el Día Nacional de la Memoria por la Verdad y la Justicia. Recordamos y honramos a quienes lucharon por un país más justo.',
    prioridad: 'media',
    activo: true,
  },
  {
    codigo: 'dia_veteranos',
    nombre: 'Día del Veterano y de los Caídos en Malvinas',
    descripcion: 'Homenaje a veteranos y caídos en la Guerra de Malvinas',
    tipo: 'feriado_nacional',
    mes: 4,
    dia: 2,
    esFechaFija: true,
    segmentacion: { genero: 'todos' },
    plantillaTitulo: 'Día del Veterano de Malvinas',
    plantillaMensaje: 'Honramos la memoria de los héroes que dieron su vida por la Patria y reconocemos a los veteranos de Malvinas. Las Malvinas son Argentinas.',
    prioridad: 'media',
    activo: true,
  },
  {
    codigo: 'dia_trabajador',
    nombre: 'Día del Trabajador',
    descripcion: 'Día Internacional del Trabajador',
    tipo: 'feriado_nacional',
    mes: 5,
    dia: 1,
    esFechaFija: true,
    segmentacion: { genero: 'todos' },
    plantillaTitulo: '¡Feliz Día del Trabajador, {{cliente.nombre}}!',
    plantillaMensaje: 'En este Día del Trabajador, desde {{empresa.nombre}} valoramos tu esfuerzo y dedicación. ¡Que tu trabajo siempre te brinde satisfacción y crecimiento!',
    prioridad: 'alta',
    activo: true,
  },
  {
    codigo: 'dia_revolucion_mayo',
    nombre: 'Día de la Revolución de Mayo',
    descripcion: 'Conmemoración de la Revolución de Mayo de 1810',
    tipo: 'feriado_nacional',
    mes: 5,
    dia: 25,
    esFechaFija: true,
    segmentacion: { genero: 'todos' },
    plantillaTitulo: '¡Viva la Patria!',
    plantillaMensaje: 'Celebramos el 25 de Mayo, fecha que marca el inicio de nuestra identidad nacional. Desde {{empresa.nombre}}, ¡Viva la Patria!',
    prioridad: 'alta',
    activo: true,
  },
  {
    codigo: 'dia_medio_ambiente',
    nombre: 'Día Mundial del Medio Ambiente',
    descripcion: 'Concientización sobre el cuidado del medio ambiente',
    tipo: 'dia_especial',
    mes: 6,
    dia: 5,
    esFechaFija: true,
    segmentacion: { genero: 'todos' },
    plantillaTitulo: 'Día del Medio Ambiente',
    plantillaMensaje: 'Hoy celebramos el Día Mundial del Medio Ambiente. En {{empresa.nombre}} nos comprometemos con prácticas sustentables. ¡Cuidemos juntos nuestro planeta!',
    prioridad: 'media',
    activo: true,
  },
  {
    codigo: 'dia_bandera',
    nombre: 'Día de la Bandera',
    descripcion: 'Conmemoración del fallecimiento de Manuel Belgrano',
    tipo: 'feriado_nacional',
    mes: 6,
    dia: 20,
    esFechaFija: true,
    segmentacion: { genero: 'todos' },
    plantillaTitulo: 'Día de la Bandera',
    plantillaMensaje: 'Honramos a Manuel Belgrano y nuestra querida bandera argentina. ¡Viva la Patria!',
    prioridad: 'media',
    activo: true,
  },
  {
    codigo: 'dia_padre',
    nombre: 'Día del Padre',
    descripcion: 'Celebración del Día del Padre (tercer domingo de junio)',
    tipo: 'dia_especial',
    mes: 6,
    dia: 0,
    esFechaFija: false,
    calculoEspecial: 'tercer_domingo_junio',
    segmentacion: { genero: 'masculino', requierePadre: true },
    plantillaTitulo: '¡Feliz Día del Padre, {{cliente.nombre}}!',
    plantillaMensaje: 'En este día tan especial, desde {{empresa.nombre}} le deseamos un muy feliz Día del Padre. ¡Que disfrute este día rodeado de quienes más lo quieren!',
    prioridad: 'alta',
    activo: true,
  },
  {
    codigo: 'dia_independencia',
    nombre: 'Día de la Independencia',
    descripcion: 'Declaración de la Independencia Argentina',
    tipo: 'feriado_nacional',
    mes: 7,
    dia: 9,
    esFechaFija: true,
    segmentacion: { genero: 'todos' },
    plantillaTitulo: '¡Feliz Día de la Independencia!',
    plantillaMensaje: 'Celebramos el 9 de Julio, día en que declaramos nuestra libertad como nación. Desde {{empresa.nombre}}, ¡Viva la Independencia Argentina!',
    prioridad: 'alta',
    activo: true,
  },
  {
    codigo: 'dia_amigo',
    nombre: 'Día del Amigo',
    descripcion: 'Celebración de la amistad',
    tipo: 'dia_especial',
    mes: 7,
    dia: 20,
    esFechaFija: true,
    segmentacion: { genero: 'todos' },
    plantillaTitulo: '¡Feliz Día del Amigo, {{cliente.nombre}}!',
    plantillaMensaje: 'En el Día del Amigo, desde {{empresa.nombre}} queremos agradecerte por tu confianza. ¡Valoramos nuestra relación y esperamos seguir acompañándote!',
    prioridad: 'alta',
    activo: true,
  },
  {
    codigo: 'dia_nino',
    nombre: 'Día del Niño',
    descripcion: 'Celebración del Día del Niño (tercer domingo de agosto)',
    tipo: 'dia_especial',
    mes: 8,
    dia: 0,
    esFechaFija: false,
    calculoEspecial: 'tercer_domingo_agosto',
    segmentacion: { genero: 'todos', requiereHijos: true },
    plantillaTitulo: '¡Feliz Día del Niño!',
    plantillaMensaje: 'En este Día del Niño, desde {{empresa.nombre}} le deseamos momentos de alegría junto a los más pequeños de la familia. ¡Que disfruten este día especial!',
    prioridad: 'alta',
    activo: true,
  },
  {
    codigo: 'dia_san_martin',
    nombre: 'Paso a la Inmortalidad del General San Martín',
    descripcion: 'Conmemoración del fallecimiento de José de San Martín',
    tipo: 'feriado_nacional',
    mes: 8,
    dia: 17,
    esFechaFija: true,
    segmentacion: { genero: 'todos' },
    plantillaTitulo: 'Homenaje al General San Martín',
    plantillaMensaje: 'Recordamos al Libertador de América, General José de San Martín. Su legado de libertad y honor perdura en nuestra nación.',
    prioridad: 'media',
    activo: true,
  },
  {
    codigo: 'dia_seguridad_vial',
    nombre: 'Día Nacional de la Seguridad Vial',
    descripcion: 'Concientización sobre seguridad vial',
    tipo: 'dia_especial',
    mes: 10,
    dia: 10,
    esFechaFija: true,
    segmentacion: { genero: 'todos' },
    plantillaTitulo: 'Día de la Seguridad Vial',
    plantillaMensaje: 'Hoy es el Día de la Seguridad Vial. Desde {{empresa.nombre}} te recordamos la importancia de cuidarnos en las calles. ¡Tu seguridad es lo primero!',
    prioridad: 'media',
    activo: true,
  },
  {
    codigo: 'dia_madre',
    nombre: 'Día de la Madre',
    descripcion: 'Celebración del Día de la Madre (tercer domingo de octubre)',
    tipo: 'dia_especial',
    mes: 10,
    dia: 0,
    esFechaFija: false,
    calculoEspecial: 'tercer_domingo_octubre',
    segmentacion: { genero: 'femenino', requiereMadre: true },
    plantillaTitulo: '¡Feliz Día de la Madre, {{cliente.nombre}}!',
    plantillaMensaje: 'En este día tan especial, desde {{empresa.nombre}} le deseamos un muy feliz Día de la Madre. ¡Que reciba todo el amor y cariño que merece!',
    prioridad: 'alta',
    activo: true,
  },
  {
    codigo: 'dia_diversidad',
    nombre: 'Día del Respeto a la Diversidad Cultural',
    descripcion: 'Día de la Diversidad Cultural Americana',
    tipo: 'feriado_nacional',
    mes: 10,
    dia: 12,
    esFechaFija: true,
    segmentacion: { genero: 'todos' },
    plantillaTitulo: 'Día de la Diversidad Cultural',
    plantillaMensaje: 'Celebramos la diversidad que nos enriquece como sociedad. Desde {{empresa.nombre}}, valoramos todas las culturas que forman nuestra identidad.',
    prioridad: 'media',
    activo: true,
  },
  {
    codigo: 'dia_soberania',
    nombre: 'Día de la Soberanía Nacional',
    descripcion: 'Conmemoración de la Batalla de la Vuelta de Obligado',
    tipo: 'feriado_nacional',
    mes: 11,
    dia: 20,
    esFechaFija: true,
    segmentacion: { genero: 'todos' },
    plantillaTitulo: 'Día de la Soberanía Nacional',
    plantillaMensaje: 'Conmemoramos el Día de la Soberanía Nacional, recordando la defensa de nuestra independencia. ¡Viva la Patria!',
    prioridad: 'media',
    activo: true,
  },
  {
    codigo: 'black_friday',
    nombre: 'Black Friday',
    descripcion: 'Día de ofertas especiales (cuarto viernes de noviembre)',
    tipo: 'comercial',
    mes: 11,
    dia: 0,
    esFechaFija: false,
    calculoEspecial: 'cuarto_viernes_noviembre',
    segmentacion: { genero: 'todos' },
    plantillaTitulo: '¡Black Friday en {{empresa.nombre}}!',
    plantillaMensaje: '¡Llegó el Black Friday! Aprovechá las mejores oportunidades inmobiliarias con condiciones especiales. ¡Consultanos hoy!',
    prioridad: 'alta',
    activo: true,
  },
  {
    codigo: 'cyber_monday',
    nombre: 'Cyber Monday',
    descripcion: 'Día de ofertas online (lunes después de Black Friday)',
    tipo: 'comercial',
    mes: 11,
    dia: 0,
    esFechaFija: false,
    calculoEspecial: 'lunes_despues_black_friday',
    segmentacion: { genero: 'todos' },
    plantillaTitulo: '¡Cyber Monday en {{empresa.nombre}}!',
    plantillaMensaje: '¡Es Cyber Monday! Las mejores oportunidades inmobiliarias te esperan. ¡No te pierdas nuestras ofertas exclusivas!',
    prioridad: 'alta',
    activo: true,
  },
  {
    codigo: 'dia_inmaculada',
    nombre: 'Día de la Inmaculada Concepción',
    descripcion: 'Festividad religiosa',
    tipo: 'feriado_nacional',
    mes: 12,
    dia: 8,
    esFechaFija: true,
    segmentacion: { genero: 'todos' },
    plantillaTitulo: 'Feliz día',
    plantillaMensaje: 'En este día especial, desde {{empresa.nombre}} le deseamos paz y bendiciones para usted y su familia.',
    prioridad: 'baja',
    activo: true,
  },
  {
    codigo: 'navidad',
    nombre: 'Navidad',
    descripcion: 'Celebración de Navidad',
    tipo: 'feriado_nacional',
    mes: 12,
    dia: 25,
    esFechaFija: true,
    segmentacion: { genero: 'todos' },
    plantillaTitulo: '¡Feliz Navidad, {{cliente.nombre}}!',
    plantillaMensaje: 'Desde {{empresa.nombre}} le deseamos una muy Feliz Navidad llena de paz, amor y alegría junto a sus seres queridos. ¡Que estos días estén llenos de bendiciones!',
    prioridad: 'alta',
    activo: true,
  },
  {
    codigo: 'aniversario_cliente',
    nombre: 'Aniversario con el Cliente',
    descripcion: 'Celebración del aniversario de relación con el cliente',
    tipo: 'dia_especial',
    mes: 0,
    dia: 0,
    esFechaFija: false,
    calculoEspecial: 'aniversario_cliente',
    segmentacion: { genero: 'todos' },
    plantillaTitulo: '¡Feliz Aniversario, {{cliente.nombre}}!',
    plantillaMensaje: 'Hoy celebramos {{aniversario}} año(s) de confianza mutua. Desde {{empresa.nombre}} agradecemos profundamente tu fidelidad. ¡Esperamos seguir acompañándote muchos años más!',
    prioridad: 'alta',
    activo: true,
  },
  {
    codigo: 'cumpleanos_cliente',
    nombre: 'Cumpleaños del Cliente',
    descripcion: 'Saludo de cumpleaños personalizado',
    tipo: 'dia_especial',
    mes: 0,
    dia: 0,
    esFechaFija: false,
    calculoEspecial: 'cumpleanos_cliente',
    segmentacion: { genero: 'todos' },
    plantillaTitulo: '¡Feliz Cumpleaños, {{cliente.nombre}}!',
    plantillaMensaje: 'En nombre de todo el equipo de {{empresa.nombre}}, te deseamos un muy feliz cumpleaños. ¡Que este nuevo año de vida esté lleno de logros y felicidad!',
    prioridad: 'alta',
    activo: true,
  },
];

module.exports = fechasImportantesArgentina;
